// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: acme/pet/v1/pet.proto

package petv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "example.com/acme/pet/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PetServiceName is the fully-qualified name of the PetService service.
	PetServiceName = "acme.pet.v1.PetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PetServiceGetPetProcedure is the fully-qualified name of the PetService's GetPet RPC.
	PetServiceGetPetProcedure = "/acme.pet.v1.PetService/GetPet"
	// PetServiceListPetsProcedure is the fully-qualified name of the PetService's ListPets RPC.
	PetServiceListPetsProcedure = "/acme.pet.v1.PetService/ListPets"
)

// PetServiceClient is a client for the acme.pet.v1.PetService service.
type PetServiceClient interface {
	GetPet(context.Context, *connect.Request[v1.GetPetRequest]) (*connect.Response[v1.GetPetResponse], error)
	ListPets(context.Context, *connect.Request[v1.ListPetsRequest]) (*connect.ServerStreamForClient[v1.ListPetsResponse], error)
}

// NewPetServiceClient constructs a client for the acme.pet.v1.PetService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	petServiceMethods := v1.File_acme_pet_v1_pet_proto.Services().ByName("PetService").Methods()
	return &petServiceClient{
		getPet: connect.NewClient[v1.GetPetRequest, v1.GetPetResponse](
			httpClient,
			baseURL+PetServiceGetPetProcedure,
			connect.WithSchema(petServiceMethods.ByName("GetPet")),
			connect.WithClientOptions(opts...),
		),
		listPets: connect.NewClient[v1.ListPetsRequest, v1.ListPetsResponse](
			httpClient,
			baseURL+PetServiceListPetsProcedure,
			connect.WithSchema(petServiceMethods.ByName("ListPets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// petServiceClient implements PetServiceClient.
type petServiceClient struct {
	getPet   *connect.Client[v1.GetPetRequest, v1.GetPetResponse]
	listPets *connect.Client[v1.ListPetsRequest, v1.ListPetsResponse]
}

// GetPet calls acme.pet.v1.PetService.GetPet.
func (c *petServiceClient) GetPet(ctx context.Context, req *connect.Request[v1.GetPetRequest]) (*connect.Response[v1.GetPetResponse], error) {
	return c.getPet.CallUnary(ctx, req)
}

// ListPets calls acme.pet.v1.PetService.ListPets.
func (c *petServiceClient) ListPets(ctx context.Context, req *connect.Request[v1.ListPetsRequest]) (*connect.ServerStreamForClient[v1.ListPetsResponse], error) {
	return c.listPets.CallServerStream(ctx, req)
}

// PetServiceHandler is an implementation of the acme.pet.v1.PetService service.
type PetServiceHandler interface {
	GetPet(context.Context, *connect.Request[v1.GetPetRequest]) (*connect.Response[v1.GetPetResponse], error)
	ListPets(context.Context, *connect.Request[v1.ListPetsRequest], *connect.ServerStream[v1.ListPetsResponse]) error
}

// NewPetServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPetServiceHandler(svc PetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	petServiceMethods := v1.File_acme_pet_v1_pet_proto.Services().ByName("PetService").Methods()
	petServiceGetPetHandler := connect.NewUnaryHandler(
		PetServiceGetPetProcedure,
		svc.GetPet,
		connect.WithSchema(petServiceMethods.ByName("GetPet")),
		connect.WithHandlerOptions(opts...),
	)
	petServiceListPetsHandler := connect.NewServerStreamHandler(
		PetServiceListPetsProcedure,
		svc.ListPets,
		connect.WithSchema(petServiceMethods.ByName("ListPets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/acme.pet.v1.PetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PetServiceGetPetProcedure:
			petServiceGetPetHandler.ServeHTTP(w, r)
		case PetServiceListPetsProcedure:
			petServiceListPetsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPetServiceHandler struct{}

func (UnimplementedPetServiceHandler) GetPet(context.Context, *connect.Request[v1.GetPetRequest]) (*connect.Response[v1.GetPetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("acme.pet.v1.PetService.GetPet is not implemented"))
}

func (UnimplementedPetServiceHandler) ListPets(context.Context, *connect.Request[v1.ListPetsRequest], *connect.ServerStream[v1.ListPetsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("acme.pet.v1.PetService.ListPets is not implemented"))
}
