#!/usr/bin/env python3
"""Compile libc++/libc++abi/libunwind from LLVM (b158b0ae6) with exnref flags."""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(os.environ.get("HOMESCOOP_ROOT", Path(__file__).resolve().parents[2]))
SLICC = Path(os.environ.get("SLICC_EMSCRIPTEN", ROOT.parent / "slicc-emscripten"))
LLVM = Path(os.environ.get("LLVM_PROJECT", SLICC / "src/llvm-project"))
CLANG = Path(os.environ.get("CLANG_HOST", SLICC / "install/bin/clang"))
CLANGXX = Path(os.environ.get("CLANGXX_HOST", SLICC / "install/bin/clang++"))
AR = Path(os.environ.get("LLVM_AR", CLANG.parent / "llvm-ar"))
SYS = Path(
    os.environ.get(
        "CXX_BUILD_SYSROOT", Path.home() / ".wasixcc/sysroot/sysroot-exnref-eh"
    )
)
OUT = Path(
    os.environ.get("CXX_RUNTIME_OUT", ROOT / "packages/wasix-sysroot/.cxx-runtimes")
)
JOBS = int(os.environ.get("JOBS", os.cpu_count() or 4))


def need(p: Path) -> None:
    if not p.exists():
        sys.exit(f"homescoop: missing {p}")


def run(cmd: list[str]) -> None:
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print("CMD:", " ".join(cmd), file=sys.stderr)
        print(r.stdout, file=sys.stderr)
        print(r.stderr, file=sys.stderr)
        raise SystemExit(r.returncode)


def resource_dir() -> str:
    return subprocess.check_output([str(CLANG), "-print-resource-dir"], text=True).strip()


def prepare_headers(hdr: Path) -> None:
    if hdr.exists():
        shutil.rmtree(hdr)
    cxx = hdr / "include/c++/v1"
    inc = hdr / "include"
    cxx.mkdir(parents=True, exist_ok=True)
    inc.mkdir(parents=True, exist_ok=True)
    # Copy LLVM headers; keep wasix __config_site for musl/threads/ABI.
    for src, dst in [
        (LLVM / "libcxx/include", cxx),
        (LLVM / "libcxxabi/include", cxx),
        (LLVM / "libunwind/include", inc),
    ]:
        for p in src.rglob("*"):
            if p.is_dir():
                continue
            if p.name in {"CMakeLists.txt"} or p.suffix == ".in":
                continue
            rel = p.relative_to(src)
            if rel.as_posix() == "__config_site":
                continue
            out = dst / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, out)
    # Prefer a LLVM-24-configured __config_site (hardening / assertion semantic).
    # Fall back to synthesizing one from wasix + required LLVM 24 macros.
    cfg_candidates = [
        OUT / "build-static/include/c++/v1/__config_site",
        SYS / "include/c++/v1/__config_site",
    ]
    cfg_src = next((p for p in cfg_candidates if p.exists()), None)
    if cfg_src is None:
        sys.exit("homescoop: no __config_site found")
    text = cfg_src.read_text()
    if "_LIBCPP_ASSERTION_SEMANTIC_DEFAULT" not in text:
        text = text.replace(
            "#define _LIBCPP_HARDENING_MODE_DEFAULT 2",
            "#define _LIBCPP_HARDENING_MODE_DEFAULT 2\n"
            "#define _LIBCPP_ASSERTION_SEMANTIC_DEFAULT 2",
        )
    if "_LIBCPP_LIBC_PICOLIBC" not in text:
        text = text.replace(
            "// __USE_MINGW_ANSI_STDIO",
            "#define _LIBCPP_LIBC_PICOLIBC 0\n"
            "#define _LIBCPP_LIBC_NEWLIB 0\n"
            "#define _LIBCPP_LIBC_LLVM_LIBC 0\n\n"
            "// __USE_MINGW_ANSI_STDIO",
        )
    (cxx / "__config_site").write_text(text)
    # __assertion_handler is generated by libc++ cmake; copy or create default.
    ah_src = OUT / "build-static/include/c++/v1/__assertion_handler"
    if ah_src.exists():
        shutil.copy2(ah_src, cxx / "__assertion_handler")
    else:
        (cxx / "__assertion_handler").write_text(
            "// generated for homescoop cxx rebuild\n"
            "#ifndef _LIBCPP___ASSERTION_HANDLER\n"
            "#define _LIBCPP___ASSERTION_HANDLER\n"
            "#include <__config>\n"
            "#include <__verbose_abort>\n"
            "#endif\n"
        )
    # LLVM 24 dropped wasi→musl locale bridging that wasix still ships. Restore it.
    wasix_locale = SYS / "include/c++/v1/__locale_dir/locale_base_api"
    musl_h = wasix_locale / "musl.h"
    if musl_h.exists():
        dest = cxx / "__locale_dir/locale_base_api"
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copy2(musl_h, dest / "musl.h")
    api = cxx / "__locale_dir/locale_base_api.h"
    if api.exists():
        t = api.read_text()
        # Prefer wasix's wasi/musl-aware locale_base_api when available.
        wasix_api = SYS / "include/c++/v1/__locale_dir/locale_base_api.h"
        if wasix_api.exists() and "musl.h" in wasix_api.read_text():
            shutil.copy2(wasix_api, api)
        elif "locale_base_api/musl.h" not in t:
            # Minimal patch: send wasi/musl to musl.h instead of ibm.h.
            t = t.replace(
                "#    include <__locale_dir/locale_base_api/ibm.h>\n",
                "#    if defined(__wasi__) || _LIBCPP_HAS_MUSL_LIBC\n"
                "#      include <__locale_dir/locale_base_api/musl.h>\n"
                "#    else\n"
                "#      include <__locale_dir/locale_base_api/ibm.h>\n"
                "#    endif\n",
                1,
            )
            api.write_text(t)


ABI_SRCS = [
    "abort_message.cpp",
    "cxa_aux_runtime.cpp",
    "cxa_default_handlers.cpp",
    "cxa_demangle.cpp",
    "cxa_exception.cpp",
    "cxa_exception_storage.cpp",
    "cxa_guard.cpp",
    "cxa_handlers.cpp",
    "cxa_personality.cpp",
    "cxa_vector.cpp",
    "cxa_virtual.cpp",
    "cxa_thread_atexit.cpp",
    "fallback_malloc.cpp",
    "private_typeinfo.cpp",
    "stdlib_exception.cpp",
    "stdlib_new_delete.cpp",
    "stdlib_stdexcept.cpp",
    "stdlib_typeinfo.cpp",
]

CXX_SRCS = [
    "algorithm.cpp",
    "any.cpp",
    "bind.cpp",
    "call_once.cpp",
    "charconv.cpp",
    "chrono.cpp",
    "error_category.cpp",
    "exception.cpp",
    "expected.cpp",
    "filesystem/directory_entry.cpp",
    "filesystem/directory_iterator.cpp",
    "filesystem/filesystem_clock.cpp",
    "filesystem/filesystem_error.cpp",
    "filesystem/operations.cpp",
    "filesystem/path.cpp",
    "functional.cpp",
    "future.cpp",
    "hash.cpp",
    "ios.cpp",
    "ios.instantiations.cpp",
    "iostream.cpp",
    "locale.cpp",
    "memory.cpp",
    "memory_resource.cpp",
    "mutex.cpp",
    "mutex_destructor.cpp",
    "new_handler.cpp",
    "new_helpers.cpp",
    "optional.cpp",
    "ostream.cpp",
    "print.cpp",
    "random.cpp",
    "random_shuffle.cpp",
    "regex.cpp",
    "stdexcept.cpp",
    "string.cpp",
    "strstream.cpp",
    "system_error.cpp",
    "thread.cpp",
    "typeinfo.cpp",
    "valarray.cpp",
    "variant.cpp",
    "vector.cpp",
    "verbose_abort.cpp",
    "atomic.cpp",
    "barrier.cpp",
    "condition_variable.cpp",
    "condition_variable_destructor.cpp",
    "shared_mutex.cpp",
    "fstream.cpp",
    "ryu/d2fixed.cpp",
    "ryu/d2s.cpp",
    "ryu/f2s.cpp",
]


def common_flags(hdr: Path, pic: bool) -> list[str]:
    tls = "global-dynamic" if pic else "local-exec"
    flags = [
        f"--target=wasm32-wasip1",
        f"--sysroot={SYS}",
        f"-resource-dir={resource_dir()}",
        "-O2",
        "-g",
        "-matomics",
        "-mbulk-memory",
        "-mmutable-globals",
        "-pthread",
        "-mthread-model",
        "posix",
        f"-ftls-model={tls}",
        "-fno-trapping-math",
        "-D_WASI_EMULATED_MMAN",
        "-D_WASI_EMULATED_SIGNAL",
        "-D_WASI_EMULATED_PROCESS_CLOCKS",
        "-fwasm-exceptions",
        "-mllvm",
        "--wasm-enable-eh",
        "-mllvm",
        "--wasm-enable-sjlj",
        "-mllvm",
        "--wasm-use-legacy-eh=false",
        "-nostdinc++",
        f"-isystem{hdr / 'include/c++/v1'}",
        f"-isystem{hdr / 'include'}",
        f"-I{LLVM / 'libcxx/src'}",
        f"-I{LLVM / 'libc'}",
        f"-I{LLVM / 'libcxxabi/include'}",
        f"-I{LLVM / 'libunwind/include'}",
        f"-I{LLVM / 'libunwind/src'}",
    ]
    if pic:
        flags += ["-fPIC", "-fvisibility=default"]
    return flags


def cxx_defs() -> list[str]:
    return [
        "-D_LIBCPP_BUILDING_LIBRARY",
        "-D_LIBCXXABI_BUILDING_LIBRARY",
        "-DLIBCXXABI_SILENT_TERMINATE",
        "-D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER",
        "-DLIBCXX_BUILDING_LIBCXXABI=1",
        "-D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS",
        "-Wno-unused-parameter",
        "-Wno-user-defined-literals",
        "-Wno-covered-switch-default",
        "-Wno-suggest-override",
        "-Wno-error",
        "-std=c++23",
    ]


def compile_variant(name: str, pic: bool, hdr: Path) -> None:
    obj = OUT / f"obj-{name}"
    inst = OUT / f"install-{name}"
    libdir = inst / "lib/wasm32-wasi"
    if obj.exists():
        shutil.rmtree(obj)
    if inst.exists():
        shutil.rmtree(inst)
    (obj / "unwind").mkdir(parents=True)
    (obj / "cxxabi").mkdir(parents=True)
    (obj / "cxx").mkdir(parents=True)
    libdir.mkdir(parents=True)

    base = common_flags(hdr, pic)
    jobs: list[tuple[str, list[str]]] = []

    uw = obj / "unwind/Unwind-wasm.c.o"
    jobs.append(
        (
            "Unwind-wasm.c",
            [
                str(CLANG),
                *base,
                "-D_LIBUNWIND_HIDE_SYMBOLS",
                "-D__WASM_EXCEPTIONS__",
                "-DNDEBUG",
                "-std=c11",
                "-c",
                str(LLVM / "libunwind/src/Unwind-wasm.c"),
                "-o",
                str(uw),
            ],
        )
    )

    for s in ABI_SRCS:
        out = obj / "cxxabi" / f"{s}.o"
        jobs.append(
            (
                s,
                [
                    str(CLANGXX),
                    *base,
                    *cxx_defs(),
                    "-c",
                    str(LLVM / "libcxxabi/src" / s),
                    "-o",
                    str(out),
                ],
            )
        )

    for s in CXX_SRCS:
        out = obj / "cxx" / f"{Path(s).name}.o"
        jobs.append(
            (
                s,
                [
                    str(CLANGXX),
                    *base,
                    *cxx_defs(),
                    "-c",
                    str(LLVM / "libcxx/src" / s),
                    "-o",
                    str(out),
                ],
            )
        )

    print(f"== compile {name} ({len(jobs)} TUs, jobs={JOBS})")
    failed = False
    with ThreadPoolExecutor(max_workers=JOBS) as ex:
        futs = {ex.submit(run, cmd): label for label, cmd in jobs}
        for fut in as_completed(futs):
            label = futs[fut]
            try:
                fut.result()
            except SystemExit:
                print(f"FAIL {label}", file=sys.stderr)
                failed = True
            except Exception as e:
                print(f"FAIL {label}: {e}", file=sys.stderr)
                failed = True
    if failed:
        sys.exit(1)

    print(f"== archive {name}")
    run([str(AR), "rcs", str(libdir / "libunwind.a"), *sorted((obj / "unwind").glob("*.o"))])
    run([str(AR), "rcs", str(libdir / "libc++abi.a"), *sorted((obj / "cxxabi").glob("*.o"))])
    run([str(AR), "rcs", str(libdir / "libc++.a"), *sorted((obj / "cxx").glob("*.o"))])
    shutil.copytree(hdr / "include", inst / "include")
    print(f"  → {libdir}")


def main() -> None:
    need(CLANG)
    need(CLANGXX)
    need(AR)
    need(LLVM / "libcxxabi/src/cxa_personality.cpp")
    need(SYS / "include/stdio.h")
    print("== manual-cxx:", subprocess.check_output([str(CLANG), "--version"], text=True).splitlines()[0])
    if (LLVM / ".git").exists():
        rev = subprocess.check_output(["git", "-C", str(LLVM), "rev-parse", "HEAD"], text=True).strip()
        print(f"   LLVM HEAD={rev}")
    OUT.mkdir(parents=True, exist_ok=True)
    hdr = OUT / "headers"
    prepare_headers(hdr)
    compile_variant("static", False, hdr)
    compile_variant("pic", True, hdr)
    print("== manual-cxx: done")


if __name__ == "__main__":
    main()
