#!/usr/bin/env python3
"""Write <prefix>/bin/llvm-config for the wasm32-wasip1-threads LLVM install.

The real llvm-config is a program for the host LLVM targets; this LLVM's host
is wasm, so consumers on the build machine (rustc's bootstrap, zig's build)
get a python3 script with the same answers instead. It is generated from the
build tree's LibraryDependencies.inc and BuildVariables.inc and finds its
prefix from its own location, so the install can move.

usage: gen-llvm-config.py <build-dir> <prefix> <host-triple>
"""
import json
import re
import sys
from pathlib import Path

build, prefix, host_triple = Path(sys.argv[1]), Path(sys.argv[2]), sys.argv[3]
inc = build / "tools/llvm-config"
deps_text = (inc / "LibraryDependencies.inc").read_text()
vars_text = (inc / "BuildVariables.inc").read_text()

components = {}
for name, lib, deps in re.findall(
    r'\{ "([^"]+)", (?:"([^"]+)"|nullptr), (?:true|false), \{([^}]*)\} \}', deps_text
):
    components[name] = {"lib": lib or None, "deps": re.findall(r'"([^"]+)"', deps)}

defines = dict(re.findall(r'#define (LLVM_\w+) "([^"]*)"', vars_text))
full_version = (build / "include/llvm/Config/llvm-config.h").read_text()
full_version = re.search(r'#define LLVM_VERSION_STRING "([^"]+)"', full_version).group(1)
major = full_version.split(".")[0]

# Only libraries that were installed (tools and utils were not built).
installed = {p.name for p in (prefix / "lib").glob("libLLVM*.a")}
components = {
    n: c for n, c in components.items() if c["lib"] is None or f"lib{c['lib']}.a" in installed
}

data = {
    "version": full_version,
    "major": major,
    "components": components,
    "targets": defines["LLVM_TARGETS_BUILT"],
    "cxxflags": defines["LLVM_CXXFLAGS"],
    "cflags": defines["LLVM_CFLAGS"],
    "cppflags": defines["LLVM_CPPFLAGS"],
    "system_libs": defines["LLVM_SYSTEM_LIBS"],
    "build_mode": defines["LLVM_BUILDMODE"],
    "host_triple": host_triple,
}

script = '''#!/usr/bin/env python3
# llvm-config for a wasm32-wasip1-threads LLVM install (generated by homescoop
# wasi-llvm/gen-llvm-config.py; answers as llvm-config would, static only).
import os, sys
D = json.loads(DATA)
prefix = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
inc, lib = os.path.join(prefix, "include"), os.path.join(prefix, "lib")

def closure(names):
    seen, order = set(), []
    def visit(n):
        if n in seen: return
        if n not in D["components"]:
            sys.exit(f"llvm-config: error: component not found: {n}")
        seen.add(n)
        for d in D["components"][n]["deps"]:
            if d in D["components"]: visit(d)
        order.append(n)
    for n in names: visit(n)
    libs = [D["components"][n]["lib"] for n in reversed(order) if D["components"][n]["lib"]]
    return libs

args = sys.argv[1:]
comps = [a for a in args if not a.startswith("-")] or ["all"]
comps = [c.lower() for c in comps]
if "all" in comps: comps = [n for n in D["components"] if D["components"][n]["lib"]]
out = []
for a in args:
    if not a.startswith("-"): continue
    if a == "--version": out.append(D["version"])
    elif a == "--prefix": out.append(prefix)
    elif a == "--bindir": out.append(os.path.join(prefix, "bin"))
    elif a == "--includedir": out.append(inc)
    elif a == "--libdir": out.append(lib)
    elif a == "--cmakedir": out.append(os.path.join(lib, "cmake", "llvm"))
    elif a == "--cppflags": out.append(f"-I{inc} {D['cppflags']}")
    elif a == "--cflags": out.append(f"-I{inc} {D['cflags']}")
    elif a == "--cxxflags": out.append(f"-I{inc} {D['cxxflags']}")
    elif a == "--ldflags": out.append(f"-L{lib}")
    elif a == "--system-libs": out.append(D["system_libs"])
    elif a == "--libs": out.append(" ".join(f"-l{l}" for l in closure(comps)))
    elif a == "--libnames": out.append(" ".join(f"lib{l}.a" for l in closure(comps)))
    elif a == "--libfiles": out.append(" ".join(os.path.join(lib, f"lib{l}.a") for l in closure(comps)))
    elif a == "--components": out.append(" ".join(sorted(D["components"])))
    elif a == "--targets-built": out.append(D["targets"])
    elif a == "--host-target": out.append(D["host_triple"])
    elif a == "--build-mode": out.append(D["build_mode"])
    elif a == "--assertion-mode": out.append("OFF")
    elif a == "--has-rtti": out.append("NO")
    elif a == "--shared-mode": out.append("static")
    elif a in ("--link-static", "--ignore-libllvm"): pass
    elif a == "--link-shared": sys.exit("llvm-config: error: this LLVM has no shared library")
    elif a == "--obj-root": out.append(prefix)
    else: sys.exit(f"llvm-config: error: unsupported option {a}")
print("\\n".join(out))
'''.replace("json.loads(DATA)", "json.loads(" + repr(json.dumps(data)) + ")").replace(
    "import os, sys", "import json, os, sys"
)
out = prefix / "bin" / "llvm-config"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(script)
out.chmod(0o755)
print(f"wrote {out} ({len(components)} components, LLVM {full_version})")
