// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: acme/pet/v1/kind.proto

package petv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PetKind int32

const (
	PetKind_PET_KIND_UNSPECIFIED PetKind = 0
	PetKind_PET_KIND_CAT         PetKind = 1
	PetKind_PET_KIND_DOG         PetKind = 2
)

// Enum value maps for PetKind.
var (
	PetKind_name = map[int32]string{
		0: "PET_KIND_UNSPECIFIED",
		1: "PET_KIND_CAT",
		2: "PET_KIND_DOG",
	}
	PetKind_value = map[string]int32{
		"PET_KIND_UNSPECIFIED": 0,
		"PET_KIND_CAT":         1,
		"PET_KIND_DOG":         2,
	}
)

func (x PetKind) Enum() *PetKind {
	p := new(PetKind)
	*p = x
	return p
}

func (x PetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_acme_pet_v1_kind_proto_enumTypes[0].Descriptor()
}

func (PetKind) Type() protoreflect.EnumType {
	return &file_acme_pet_v1_kind_proto_enumTypes[0]
}

func (x PetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PetKind.Descriptor instead.
func (PetKind) EnumDescriptor() ([]byte, []int) {
	return file_acme_pet_v1_kind_proto_rawDescGZIP(), []int{0}
}

var File_acme_pet_v1_kind_proto protoreflect.FileDescriptor

const file_acme_pet_v1_kind_proto_rawDesc = "" +
	"\n" +
	"\x16acme/pet/v1/kind.proto\x12\vacme.pet.v1*G\n" +
	"\aPetKind\x12\x18\n" +
	"\x14PET_KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPET_KIND_CAT\x10\x01\x12\x10\n" +
	"\fPET_KIND_DOG\x10\x02B\x1fZ\x1dexample.com/acme/pet/v1;petv1b\x06proto3"

var (
	file_acme_pet_v1_kind_proto_rawDescOnce sync.Once
	file_acme_pet_v1_kind_proto_rawDescData []byte
)

func file_acme_pet_v1_kind_proto_rawDescGZIP() []byte {
	file_acme_pet_v1_kind_proto_rawDescOnce.Do(func() {
		file_acme_pet_v1_kind_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_pet_v1_kind_proto_rawDesc), len(file_acme_pet_v1_kind_proto_rawDesc)))
	})
	return file_acme_pet_v1_kind_proto_rawDescData
}

var file_acme_pet_v1_kind_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_acme_pet_v1_kind_proto_goTypes = []any{
	(PetKind)(0), // 0: acme.pet.v1.PetKind
}
var file_acme_pet_v1_kind_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_acme_pet_v1_kind_proto_init() }
func file_acme_pet_v1_kind_proto_init() {
	if File_acme_pet_v1_kind_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_pet_v1_kind_proto_rawDesc), len(file_acme_pet_v1_kind_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_pet_v1_kind_proto_goTypes,
		DependencyIndexes: file_acme_pet_v1_kind_proto_depIdxs,
		EnumInfos:         file_acme_pet_v1_kind_proto_enumTypes,
	}.Build()
	File_acme_pet_v1_kind_proto = out.File
	file_acme_pet_v1_kind_proto_goTypes = nil
	file_acme_pet_v1_kind_proto_depIdxs = nil
}
