// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: acme/pet/v1/pet.proto

package petv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pet struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind    PetKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=acme.pet.v1.PetKind" json:"kind,omitempty"`
	Age     int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Adopted *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=adopted,proto3" json:"adopted,omitempty"`
	Tags    []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Labels  map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Owner:
	//
	//	*Pet_Person
	//	*Pet_Shelter
	Owner         isPet_Owner `protobuf_oneof:"owner"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pet) Reset() {
	*x = Pet{}
	mi := &file_acme_pet_v1_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pet) ProtoMessage() {}

func (x *Pet) ProtoReflect() protoreflect.Message {
	mi := &file_acme_pet_v1_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pet.ProtoReflect.Descriptor instead.
func (*Pet) Descriptor() ([]byte, []int) {
	return file_acme_pet_v1_pet_proto_rawDescGZIP(), []int{0}
}

func (x *Pet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pet) GetKind() PetKind {
	if x != nil {
		return x.Kind
	}
	return PetKind_PET_KIND_UNSPECIFIED
}

func (x *Pet) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Pet) GetAdopted() *timestamppb.Timestamp {
	if x != nil {
		return x.Adopted
	}
	return nil
}

func (x *Pet) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Pet) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Pet) GetOwner() isPet_Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Pet) GetPerson() string {
	if x != nil {
		if x, ok := x.Owner.(*Pet_Person); ok {
			return x.Person
		}
	}
	return ""
}

func (x *Pet) GetShelter() string {
	if x != nil {
		if x, ok := x.Owner.(*Pet_Shelter); ok {
			return x.Shelter
		}
	}
	return ""
}

type isPet_Owner interface {
	isPet_Owner()
}

type Pet_Person struct {
	Person string `protobuf:"bytes,7,opt,name=person,proto3,oneof"`
}

type Pet_Shelter struct {
	Shelter string `protobuf:"bytes,8,opt,name=shelter,proto3,oneof"`
}

func (*Pet_Person) isPet_Owner() {}

func (*Pet_Shelter) isPet_Owner() {}

var File_acme_pet_v1_pet_proto protoreflect.FileDescriptor

const file_acme_pet_v1_pet_proto_rawDesc = "" +
	"\n" +
	"\x15acme/pet/v1/pet.proto\x12\vacme.pet.v1\x1a\x16acme/pet/v1/kind.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x02\n" +
	"\x03Pet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x14.acme.pet.v1.PetKindR\x04kind\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x124\n" +
	"\aadopted\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aadopted\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x124\n" +
	"\x06labels\x18\x06 \x03(\v2\x1c.acme.pet.v1.Pet.LabelsEntryR\x06labels\x12\x18\n" +
	"\x06person\x18\a \x01(\tH\x00R\x06person\x12\x1a\n" +
	"\ashelter\x18\b \x01(\tH\x00R\ashelter\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05ownerB\x1fZ\x1dexample.com/acme/pet/v1;petv1b\x06proto3"

var (
	file_acme_pet_v1_pet_proto_rawDescOnce sync.Once
	file_acme_pet_v1_pet_proto_rawDescData []byte
)

func file_acme_pet_v1_pet_proto_rawDescGZIP() []byte {
	file_acme_pet_v1_pet_proto_rawDescOnce.Do(func() {
		file_acme_pet_v1_pet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acme_pet_v1_pet_proto_rawDesc), len(file_acme_pet_v1_pet_proto_rawDesc)))
	})
	return file_acme_pet_v1_pet_proto_rawDescData
}

var file_acme_pet_v1_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acme_pet_v1_pet_proto_goTypes = []any{
	(*Pet)(nil),                   // 0: acme.pet.v1.Pet
	nil,                           // 1: acme.pet.v1.Pet.LabelsEntry
	(PetKind)(0),                  // 2: acme.pet.v1.PetKind
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_acme_pet_v1_pet_proto_depIdxs = []int32{
	2, // 0: acme.pet.v1.Pet.kind:type_name -> acme.pet.v1.PetKind
	3, // 1: acme.pet.v1.Pet.adopted:type_name -> google.protobuf.Timestamp
	1, // 2: acme.pet.v1.Pet.labels:type_name -> acme.pet.v1.Pet.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_acme_pet_v1_pet_proto_init() }
func file_acme_pet_v1_pet_proto_init() {
	if File_acme_pet_v1_pet_proto != nil {
		return
	}
	file_acme_pet_v1_kind_proto_init()
	file_acme_pet_v1_pet_proto_msgTypes[0].OneofWrappers = []any{
		(*Pet_Person)(nil),
		(*Pet_Shelter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acme_pet_v1_pet_proto_rawDesc), len(file_acme_pet_v1_pet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acme_pet_v1_pet_proto_goTypes,
		DependencyIndexes: file_acme_pet_v1_pet_proto_depIdxs,
		MessageInfos:      file_acme_pet_v1_pet_proto_msgTypes,
	}.Build()
	File_acme_pet_v1_pet_proto = out.File
	file_acme_pet_v1_pet_proto_goTypes = nil
	file_acme_pet_v1_pet_proto_depIdxs = nil
}
